---
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker).
-- The xboot exporter place in xboot/documents/TexturePacker/xboot-exporter directory
-- 
-- $TexturePacker:SmartUpdate:74b8414966e9e73926b54c9099432812$
--

return {
	texture = "cnum.png",
	width = 557,
	height = 113,
	frames = {
		["1.png"] = { x = 446, y = 2, width = 109, height = 109 },
		["2.png"] = { x = 335, y = 2, width = 109, height = 109 },
		["3.png"] = { x = 224, y = 2, width = 109, height = 109 },
		["4.png"] = { x = 113, y = 2, width = 109, height = 109 },
		["5.png"] = { x = 2, y = 2, width = 109, height = 109 },
	},
}
