--
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker).
-- {{smartUpdateKey}}
--
-- local packer = TexturePacker:new("mypacker")
--

return {
	texture = "{{texture.fullName}}",
	width = {{texture.size.width}},
	height = {{texture.size.height}},
	frames = {{% for sprite in allSprites %}
		["{{sprite.fullName}}"] = {
			frame = {x = {{sprite.frameRect.x}}, y = {{sprite.frameRect.y}}, width = {{sprite.frameRect.width}}, height = {{sprite.frameRect.height}}},
			source = {x = {{sprite.cornerOffset.x}}, y = {{sprite.cornerOffset.y}}, width = {{sprite.untrimmedSize.width}}, height = {{sprite.untrimmedSize.height}}},
        },{% endfor %}
	},
}
