/* Using X-Macro technique to define everything once
 * http://en.wikipedia.org/wiki/X_Macro
 *
 * X macro is for minimal set of supports for library itself
 */

X(ADC,             "adc")
X(AUDIO,           "audio")
X(BATTERY,         "battery")
X(BLOCK,           "block")
X(BUZZER,          "buzzer")
X(CLK,             "clk")
X(CLOCKEVENT,      "clockevent")
X(CLOCKSOURCE,     "clocksource")
X(COMPASS,         "compass")
X(CONSOLE,         "console")
X(DAC,             "dac")
X(DISK,            "disk")
X(FRAMEBUFFER,     "framebuffer")
X(GMETER,          "gmeter")
X(GPIOCHIP,        "gpiochip")
X(GYROSCOPE,       "gyroscope")
X(HYGROMETER,      "hygrometer")
X(I2C,             "i2c")
X(INPUT,           "input")
X(IRQCHIP,         "irqchip")
X(LASERSCAN,       "laserscan")
X(LED,             "led")
X(LEDSTRIP,        "ledstrip")
X(LEDTRIGGER,      "ledtrigger")
X(LIGHT,           "light")
X(MOTOR,           "motor")
X(NVMEM,           "nvmem")
X(PRESSURE,        "pressure")
X(PROXIMITY,       "proximity")
X(PWM,             "pwm")
X(REGULATOR,       "regulator")
X(RESETCHIP,       "resetchip")
X(RNG,             "rng")
X(RTC,             "rtc")
X(SDHCI,           "sdhci")
X(SERVO,           "servo")
X(SPI,             "spi")
X(STEPPER,         "stepper")
X(THERMOMETER,     "thermometer")
X(UART,            "uart")
X(VIBRATOR,        "vibrator")
X(WATCHDOG,        "watchdog")
