---
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker).
-- The xboot exporter place in xboot/documents/texture-packer/xboot-exporter directory
-- 
-- {{smartUpdateKey}}
--

return {
	texture = "{{texture.fullName}}",
	width = {{texture.size.width}},
	height = {{texture.size.height}},
	frames = {{% for sprite in allSprites %}
		["{{sprite.fullName}}"] = { x = {{sprite.frameRect.x}}, y = {{sprite.frameRect.y}}, width = {{sprite.frameRect.width}}, height = {{sprite.frameRect.height}} },{% endfor %}
	},
}
