#ifndef __REALVIEW_REG_GPIO_H__
#define __REALVIEW_REG_GPIO_H__

#define REALVIEW_GPIO0(x)			(x)
#define REALVIEW_GPIO1(x)			(x + 8)
#define REALVIEW_GPIO2(x)			(x + 16)

#define REALVIEW_GPIO0_BASE			(0x10013000)
#define REALVIEW_GPIO1_BASE			(0x10014000)
#define REALVIEW_GPIO2_BASE			(0x10015000)

#define REALVIEW_GPIO_OFFSET_DIR	(0x400)
#define REALVIEW_GPIO_OFFSET_IS		(0x404)
#define REALVIEW_GPIO_OFFSET_IBE	(0x408)
#define REALVIEW_GPIO_OFFSET_IEV	(0x40C)
#define REALVIEW_GPIO_OFFSET_IE		(0x410)
#define REALVIEW_GPIO_OFFSET_RIS	(0x414)
#define REALVIEW_GPIO_OFFSET_MIS	(0x418)
#define REALVIEW_GPIO_OFFSET_IC		(0x41C)

#endif /* __REALVIEW_REG_GPIO_H__ */
