---
-- The 'TexturePacker' class specifies a texture packer.
-- A texture packer is a large image which contains many smaller sub-images.
-- 
-- Using TexturePacker tools to export packer files.
-- http://www.codeandweb.com/texturepacker
--
-- @module TexturePacker
local M = class()

---
-- Creates a new 'TexturePacker' object.
--
-- @function [parent=#TexturePacker] new
-- @param packer (string) The path of packer file that was generated by texturepacker.
-- @return #TexturePacker
function M:init(packer)
	self.packer = require(packer)
	self.texture = Texture.new(self.packer.texture)
	self.caches = {}
end

--- 
-- Returns the texture of texture packer.
-- 
-- @function [parent=#TexturePacker] getTexture
-- @param self
-- @param name (string)
-- @return 'Texture' object that specifies name within the texture pack.
function M:getTexture(name)
	if not name then
		return nil
	end

	if not self.caches[name] then
		local frame = self.packer.frames[name]
		if frame then
			self.caches[name] = self.texture:region(frame.x, frame.y, frame.width, frame.height)
		end
	end

	return self.caches[name]
end

return M
